# Generated by Django 5.2.8 on 2025-12-01 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hashtag', models.CharField(max_length=100, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_metadata', models.JSONField()),
                ('shards_metadata', models.JSONField()),
                ('file_thumbnail', models.JSONField(blank=True, null=True)),
                ('file_trailer', models.JSONField(blank=True, null=True)),
                ('file_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], max_length=20)),
                ('status', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('private', 'Private'), ('schedule', 'Schedule'), ('pending', 'Pending'), ('deleted', 'Deleted')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('unlock_price', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('master_key', models.BinaryField(blank=True, null=True)),
                ('nonce', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaHashtag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.hashtag')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='hashtags',
            field=models.ManyToManyField(related_name='media_hashtags', through='media.MediaHashtag', to='media.hashtag'),
        ),
        migrations.CreateModel(
            name='Unlock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unlock_type', models.CharField(choices=[('permanent', 'Permanent'), ('session', 'Session'), ('24h', '24H')], max_length=20)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='mediahashtag',
            constraint=models.UniqueConstraint(fields=('media', 'hashtag'), name='unique_media_hashtag'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['status', 'is_approved', 'user_id'], name='idx_load_media_feed'),
        ),
    ]
