# Generated by Django 5.2.8 on 2025-11-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='unlock_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
