# Generated by Django 5.2.6 on 2025-10-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('canceled', 'Canceled'), ('failed', 'Failed')], max_length=10),
        ),
    ]
